# Generated by Django 2.2.5 on 2020-03-07 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participations',
            name='is_check_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participations',
            name='Game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Game'),
        ),
        migrations.AlterField(
            model_name='participations',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
