# Generated by Django 2.2.5 on 2020-01-05 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_user_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('game_name', models.CharField(max_length=50, null=True)),
                ('num_people', models.IntegerField(default=0)),
                ('reception_start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('reception_end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('game_start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('game_end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('outline', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
