# Generated by Django 2.2.5 on 2020-03-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='outline',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
